Algoritmo "Salario_e_percentagem"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bruno Oliveira
// Data atual  : 21/09/2017
Var
Salario,valoraumento,aumento :real

Inicio
escreva ("Qual o valor do salario?")
leia (Salario)
escreva ("Qual o aumento do salario?")
leia (aumento)
valoraumento <- salario * aumento
escreva ("o novo salario é" , salario + valoraumento)
Fimalgoritmo